version: '3'
services:
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  cassandra:
    image: cassandra:4.0.0
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: Test Cluster
      CASSANDRA_KEYSPACE_NAME: crypto
      CASSANDRA_LISTEN_ADDRESS: 127.0.0.1
      
  cqlsh:
    image: cassandra:4.0.0
    command: cqlsh cassandra
    depends_on:
      - cassandra

  spark:
    image: bitnami/spark:3.1.2
    ports:
      - 4040:4040
